### ISSUE TITLE
Error in SQLAlchemy

### ISSUE THREAD

**Issue by Xumeiquer** [opencve/opencve#71] opened 2021-02-25 12:06 UTC
## Expected Behavior
OpenCVE to be working withput DB issues

## Actual Behavior
Running OpenCVE webserver command raises an error.

## Steps to Reproduce the Problem

```sh
$ opencve webserver
Traceback (most recent call last):
  File "C:\projects\opencve\sbox\Lib\site-packages\opencve\cli.py", line 5, in <module>
    from opencve import __version__
  File "C:\projects\opencve\sbox\lib\site-packages\opencve\__init__.py", line 66, in <module>
    import_submodules(__name__, ("models", "controllers", "checks", "tasks"))
  File "C:\projects\opencve\sbox\lib\site-packages\opencve\__init__.py", line 51, in import_submodules
    for loader, name, is_pkg in pkgutil.walk_packages(package.__path__):
  File "C:\Program Files\Python39\lib\pkgutil.py", line 93, in walk_packages
    __import__(info.name)
  File "C:\projects\opencve\sbox\Lib\site-packages\opencve\models\__init__.py", line 33, in <module>
    users_vendors = db.Table(
  File "C:\projects\opencve\sbox\lib\site-packages\flask_sqlalchemy\__init__.py", line 58, in _make_table
    return sqlalchemy.Table(*args, **kwargs)
  File "<string>", line 2, in __new__
  File "C:\projects\opencve\sbox\lib\site-packages\sqlalchemy\util\deprecations.py", line 130, in warned
    return fn(*args, **kwargs)
  File "C:\projects\opencve\sbox\lib\site-packages\sqlalchemy\sql\schema.py", line 473, in __new__
    raise exc.InvalidRequestError(
sqlalchemy.exc.InvalidRequestError: Table 'users_vendors' is already defined for this MetaData instance.  Specify 'extend_existing=True' to redefine options and columns on an existing Table object.
```

## Specifications

  - OpenCVE version: 1.0.2
  - Python version: 3.9
  - Platform: Windows

**Comment by ncrocfer** [comment] 2021-03-28 17:53
Can you try with Python <=3.8 ? List of supported version here : https://github.com/opencve/opencve/blob/master/setup.py#L43

If it works it's a problem on Windows, and as already said OpenCVE doesn't support it. In this case we'll close this issue, because it will not change in the future.

If the problem is still here it means it's linked to Python3.9, which is indeed not yet supported but will of course be. In this case this issue will stay opened until the fix.

**Comment by ncrocfer** [comment] 2021-06-02 06:16
Closed due to inactivity.

**Closed by ncrocfer** 2021-06-02 06:16 UTC
