### ISSUE TITLE
Cant register new user, error send mail

### ISSUE THREAD

**Issue by thont1zz** [opencve/opencve#193] opened 2022-05-01 03:21 UTC

**Comment by thont1zz** [comment] 2022-05-01 03:24
I deploy opencve to K8s, when I register new user, an error show: SMTP Connection error: Check your MAIL_SERVER and MAIL_PORT settings.
<img width="1052" alt="Screen Shot 2022-05-01 at 10 23 22" src="https://user-images.githubusercontent.com/84005956/166130835-30a7c191-efc1-40c1-a0b4-1031e28e0f98.png">

**Comment by higoje** [comment] 2022-05-09 13:46
HI,
I can't register a new user on site https://www.opencve.io/register too. I not receive that email.

**Comment by ncrocfer** [comment] 2022-08-13 16:03
Closing this issue because the problem is not related to OpenCVE itself but rather to the SMTP server of the user. Check the doc for the configuration (https://docs.opencve.io/settings/#smtp_server).

**Closed by ncrocfer** 2022-08-13 16:03 UTC
