### ISSUE TITLE
jsmin==2.2.2 in requirements.txt causes install failure on Ubuntu 20.04 LTS due to missing use_2to3.

### ISSUE THREAD

**Issue by tussock** [opencve/opencve#239] opened 2022-10-25 22:40 UTC
## Expected Behavior
Using a later version of jsmin that does not require use_2to3. setuptools as at V58 no longer supports use_2to3 - see [here](https://setuptools.pypa.io/en/latest/history.html#v58-0-0) for details.

## Actual Behavior

![Screenshot 2022-10-26 at 11 33 05 AM](https://user-images.githubusercontent.com/811473/197894743-a746b181-a8db-4660-90c4-d13c3ba34877.png)

Install of jsmin fails with "use_2to3 is invalid".

## Steps to Reproduce the Problem

On a fresh install of ubuntu server 20.04 (with postgresql + tools already installed), run the command:
`pip install opencve`

Note that the cause is probably that requirements.txt specifies only version 2.2.2 of jsmin, which is old and obsolete. Is there a reason that only this version can be used?

## Specifications

  - OpenCVE version: (latest, pulled from pip. "opencve-1.3.0-py3-none-any")
  - Python version: (3.10.6)
  - Platform: (Ubuntu 20.04.1 LTS).

## Screenshots (optional)

(attached).

**Comment by LukaszC86** [comment] 2022-11-10 09:00
I had the same issue with installation on Ubuntu 22.04. Since current OpenCVE's code is not really compatible with Python 3.10, the workaround for me was to create virtual environment using miniconda with Python 3.7, downgrade setuptools to version 58, then isntall opencve:

`conda create -n opencve-env python=3.7`
`conda activate opencve-env`
`pip install setuptools==58`
`pip install opencve`

I hope it will help you too. 😉

**Comment by ncrocfer** [comment] 2022-11-15 10:20
In fact, as @LukaszC86 said it, the problem is linked to Python 3.10. OpenCVE doesn't support it because of the [Flask-User](https://github.com/lingthio/Flask-User) requirement which is no more maintained.

The solution I found is to refactor the tool and provide an OpenCVE 2.0 version , based this time on Django (to avoid this kind of errors in the future because Django already handles the basic features like users management).

**Comment by tussock** [comment] 2022-11-17 01:54
Thanks for the comments. I've switched to the Docker image which works well.

**Comment by firmianay** [comment] 2023-02-23 05:35
Can't find the call of cssmin and jsmin in the code, it seems that it can be deleted?

**Comment by ncrocfer** [comment] 2023-02-23 06:35
@firmianay what do you you mean by "it seems it can be deleted"? I don't understand your question.

**Comment by firmianay** [comment] 2023-02-23 07:00
@ncrocfer That is, these two packages are not used and can be deleted from requirements.txt

**Comment by ncrocfer** [comment] 2023-02-24 06:32
I'm not sure you read the full issue here before asking your question. 

Please check this comment https://github.com/opencve/opencve/issues/239#issuecomment-1315098401. As I said in it I refactored OpenCVE in Django so the `cssmin` and `jsmin` packages will not be used anymore (before you ask me as you did in other issue: no I don't have ETA to give you as this is a free tool done in my free time...).

So if you encounter the same issue as this one, please use a lower version of Python. Then when OpenCVE 2.0 will be released you will be able to upgrade it.

**Comment by chrisarrow** [comment] 2023-04-18 00:47
> Thanks for the comments. I've switched to the Docker image which works well.

Unfortunately the Docker image is giving me the same error you had originally. Any suggestions?

**Comment by TexGG** [comment] 2023-04-25 14:20
The "requirements.txt" should be updated with "jsmin==3.0.1" instead of "jsmin==2.2.2" . It is an update of the library that remove the dependency problem.
But since the docker getting the content of the repository, it always get the "wrong requirements.txt". Si there is 2 possibilities in that case : 
* clone the repository, modify the "requirements.txt" and change the "OPENCVE_REPOSITORY" in the ".env" to your repository
* add this ligne right before "RUN python3 -m pip install /opencve/" : 
   * RUN sed -i s/jsmin==2\\.2\\.2/jsmin==3.0.1/g /opencve/requirements.txt

Personnaly, I did the second solution and it works great ATM.

**Comment by ncrocfer** [comment] 2023-06-04 08:44
The 1.4.1 version of OpenCVE fixing this jsmin issue has been released this week: https://github.com/opencve/opencve/releases/tag/v1.4.1

**Closed by ncrocfer** 2023-06-04 08:44 UTC
Labels: bug
