### ISSUE TITLE
The module psycopg is not working

### ISSUE THREAD

**Issue by Xumeiquer** [opencve/opencve#64] opened 2021-02-18 15:45 UTC
## Expected Behavior
The command `opencve update-db` works properly

## Actual Behavior
The command `opencve update-db` is roughing throwing an error.

## Steps to Reproduce the Problem
```python
C:\projects\opencve> opencve upgrade-db
Traceback (most recent call last):
  File "C:\Program Files\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\projects\opencve\sbox\Scripts\opencve.exe\__main__.py", line 7, in <module>
  File "c:\projects\opencve\sbox\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "c:\projects\opencve\sbox\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "c:\projects\opencve\sbox\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\projects\opencve\sbox\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\projects\opencve\sbox\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "c:\projects\opencve\sbox\lib\site-packages\click\decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "c:\projects\opencve\sbox\lib\site-packages\opencve\commands\__init__.py", line 39, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "c:\projects\opencve\sbox\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "c:\projects\opencve\sbox\lib\site-packages\click\decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "c:\projects\opencve\sbox\lib\site-packages\flask\cli.py", line 412, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "c:\projects\opencve\sbox\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "c:\projects\opencve\sbox\lib\site-packages\opencve\commands\upgrade_db.py", line 16, in upgrade_db
    upgrade(directory=str(migrations_path))
  File "c:\projects\opencve\sbox\lib\site-packages\flask_migrate\__init__.py", line 95, in wrapped
    f(*args, **kwargs)
  File "c:\projects\opencve\sbox\lib\site-packages\flask_migrate\__init__.py", line 280, in upgrade
    command.upgrade(config, revision, sql=sql, tag=tag)
  File "c:\projects\opencve\sbox\lib\site-packages\alembic\command.py", line 294, in upgrade
    script.run_env()
  File "c:\projects\opencve\sbox\lib\site-packages\alembic\script\base.py", line 481, in run_env
    util.load_python_file(self.dir, "env.py")
  File "c:\projects\opencve\sbox\lib\site-packages\alembic\util\pyfiles.py", line 97, in load_python_file
    module = load_module_py(module_id, path)
  File "c:\projects\opencve\sbox\lib\site-packages\alembic\util\compat.py", line 182, in load_module_py
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "C:\projects\opencve\sbox\Lib\site-packages\opencve\migrations\env.py", line 94, in <module>
    run_migrations_online()
  File "C:\projects\opencve\sbox\Lib\site-packages\opencve\migrations\env.py", line 70, in run_migrations_online
    engine = engine_from_config(
  File "c:\projects\opencve\sbox\lib\site-packages\sqlalchemy\engine\__init__.py", line 466, in engine_from_config
    return create_engine(url, **options)
  File "c:\projects\opencve\sbox\lib\site-packages\sqlalchemy\engine\__init__.py", line 423, in create_engine
    return strategy.create(*args, **kwargs)
  File "c:\projects\opencve\sbox\lib\site-packages\sqlalchemy\engine\strategies.py", line 87, in create
    dbapi = dialect_cls.dbapi(**dbapi_args)
  File "c:\projects\opencve\sbox\lib\site-packages\sqlalchemy\dialects\postgresql\psycopg2.py", line 605, in dbapi
    import psycopg2
  File "c:\projects\opencve\sbox\lib\site-packages\psycopg2\__init__.py", line 50, in <module>
    from psycopg2._psycopg import (                     # noqa
ImportError: DLL load failed while importing _psycopg: The specified module could not be found.
```

## Specifications

  - OpenCVE version: 1.0.2
  - Python version: 3.9.1
  - Platform: Windows

## Solution

Update the requirements for psycopg2-binary to version 2.8.6.

**Comment by ncrocfer** [comment] 2021-03-28 17:53
Can you try with Python <=3.8 ? List of supported version here : https://github.com/opencve/opencve/blob/master/setup.py#L43

If it works it's a problem on Windows, and as already said OpenCVE doesn't support it. In this case we'll close this issue, because it will not change in the future.

If the problem is still here it means it's linked to Python3.9, which is indeed not yet supported but will of course be. In this case this issue will stay opened until the fix.

**Comment by ncrocfer** [comment] 2021-06-02 06:16
Closed due to inactivity.

**Closed by ncrocfer** 2021-06-02 06:16 UTC
