### ISSUE TITLE
opencve webserver fails with connection already in use

### ISSUE THREAD

**Issue by stedeluxe** [opencve/opencve#24] opened 2021-01-06 15:02 UTC
Hi All
After working through the install steps, finally hitting my head against this...

$ opencve webserver
[2021-01-06 14:45:24 +0000] [5395] [INFO] Starting gunicorn 20.0.4
[2021-01-06 14:45:24 +0000] [5395] [ERROR] Connection in use: ('127.0.0.1', 8000)
[2021-01-06 14:45:24 +0000] [5395] [ERROR] Retrying in 1 second.
[2021-01-06 14:45:25 +0000] [5395] [ERROR] Connection in use: ('127.0.0.1', 8000)

opencve.cfg has the **server_name** set to the static IP address of the server & have tried rebooting and also changing the defined addresses fro the redis comms from127.0.0.1 to the static IP and back again - still the same issue.

**Comment by ldurnez** [comment] 2021-01-06 20:23
Hi,

It seems something is already using the port 8000 on your server. Can you try with another port, for example 8001:
$ opencve webserver -b 127.0.0.1:8001

**Comment by stedeluxe** [comment] 2021-01-07 14:48
Thanks - invoking that manually worked, but it seems the opencve.cfg file is being ignored. I amended the server_name definition and ran the **opencve webserver** command again and hit the exact same error as before:

Connection in use: ('127.0.0.1', 8000)

Shouldn't the **opencve webserver** command read the config file when executed ?

**Comment by ncrocfer** [comment] 2021-01-07 16:18
The `server_name` configuration refers to the Flask `SERVER_NAME` config : https://flask.palletsprojects.com/en/1.1.x/config/#SERVER_NAME

Flask internally uses it for several things, like generate full URL or handle subdomains. It's useful for example in OpenCVE to generate full URLs in your report emails : https://github.com/opencve/opencve/blob/9da7a8034c1646dd5c206b89e7749b990b896858/opencve/tasks/reports.py#L118

The webserver command uses Gunicorn, so you need to specify the `-b` or `--bind` option to configure it. After that you will need to change the `server_name` configuration to be the same (so the links in your emails will redirect to your OpenCVE instance URL).

We're working on a complete user documentation (instead a simple README), we'll inform users about that in it. I close this issue as it's not a bug ;)

**Closed by ncrocfer** 2021-01-07 16:18 UTC

**Comment by stedeluxe** [comment] 2021-01-07 17:02
Thanks Nicolas, much appreciated. The documentation is really needed, hope you guys will finish it soon !

As for the update on the webserver command, its worth noting for the documentation, that it actually is a bug, because the simple **opencve webserver** command alone without the **-b N.N.N.N:8001** doesn't open the webserver correctly.

**Comment by ncrocfer** [comment] 2021-01-07 17:59
@ldurnez proposed you `-b 8001` because your issue was `[2021-01-06 14:45:25 +0000] [5395] [ERROR] Connection in use: ('127.0.0.1', 8000)`.

It means you have something other running on this port... So no I can confirm you it's in your side, `opencve webserver` works well without the `-b` arg ;)

Stop the other deamon or change your opencve port.
