### ISSUE TITLE
Subscriptions and Alerts problem

### ISSUE THREAD

**Issue by Chessi99** [opencve/opencve#31] opened 2021-01-08 18:55 UTC
Hi all,  I have enabled all notifications in users' profiles but they don't receive emails when a CVE is created/updated. Also, users are subscribed to vendors and products, but Reports tab still shows the message "**_No report yet. Did you subscribe to vendors or products ?_**" . How can I solve it?

Apart from these issues, I want to know how can I edit the register email template, I can't find it. 

Cheers, 
Chessi

**Comment by ncrocfer** [comment] 2021-01-08 19:25
Hi @Chessi99 ,
Can you copy paste the worker logs here ? It will show if events / alerts / reports have well been created.

**Comment by Chessi99** [comment] 2021-01-08 19:30
[2021-01-08 16:24:18,402: INFO/ForkPoolWorker-3] HANDLE_ALERTS[f1adc9ca-ff73-4b0c-9a75-8e82fb6a7b84]: Checking for new alerts...
[2021-01-08 16:24:18,405: INFO/ForkPoolWorker-3] HANDLE_ALERTS[f1adc9ca-ff73-4b0c-9a75-8e82fb6a7b84]: No CVE to review
[2021-01-08 16:24:18,407: INFO/MainProcess] Received task: HANDLE_REPORTS[aab76637-f87c-4351-840b-90428276dd0d]
[2021-01-08 16:24:18,407: INFO/ForkPoolWorker-3] Task HANDLE_ALERTS[f1adc9ca-ff73-4b0c-9a75-8e82fb6a7b84] succeeded in 0.005175583064556122s: None
[2021-01-08 16:24:18,409: INFO/ForkPoolWorker-5] HANDLE_REPORTS[aab76637-f87c-4351-840b-90428276dd0d]: Get the users who want to always receive email...
[2021-01-08 16:24:18,411: INFO/ForkPoolWorker-5] HANDLE_REPORTS[aab76637-f87c-4351-840b-90428276dd0d]: No alert to send.
[2021-01-08 16:24:18,412: INFO/ForkPoolWorker-5] Task HANDLE_REPORTS[aab76637-f87c-4351-840b-90428276dd0d] succeeded in 0.0041163950227200985s: None

**Comment by ncrocfer** [comment] 2021-01-08 19:54
`No CVE to review` : you send the bad logs. Please paste interesting ones, with CVE to review.

For information the workflow is :
- create_event -> new CVE are detected (or changes in existing ones)
- create_alerts -> alerts are created according users preferences (frequency notifications, filters...)
- create_reports -> alerts are group into reports and are sent to users by email

So you need to have new CVE, with correct user subscriptions. If it's the case the logs will show it.

**Comment by DaniKawaii** [comment] 2021-01-08 20:30
Hello, I have a similar issue. I have an user subscribed to vendors and products, now he received 3 reports (almost at the same time) in Reports tab, but he didn't receive any email about the reports.

Here is user notifications configuration:
![image](https://user-images.githubusercontent.com/42950513/104060308-76ec1780-51d5-11eb-8f32-99467d818fa8.png)

Here are the reports:
![image](https://user-images.githubusercontent.com/42950513/104060206-5328d180-51d5-11eb-9632-7ce01d88b6d1.png)
Reports with 0 alerts can't be accessed, they throw 500 error.

The first report appeared like this:
![image](https://user-images.githubusercontent.com/42950513/104060423-a13dd500-51d5-11eb-88fc-7b6d8464c007.png)
Then, a new report appeared a few minutes after the first one (first one became inaccessible):
![image](https://user-images.githubusercontent.com/42950513/104060458-b155b480-51d5-11eb-8ea2-e7a2ad1056ad.png)
Then a third report appeared after a few minutes (I think hour is wrong in that report):
![image](https://user-images.githubusercontent.com/42950513/104060525-c9c5cf00-51d5-11eb-9297-d30f6c3c6feb.png)

But user never received emails about these reports, he can only see then inside the web.
How can I delete those "0 alert" reports? And how often do reports appear?

And I also want to know where register email template is, I need to edit it too.

Thanks!

**Comment by ncrocfer** [comment] 2021-01-08 21:55
Can you give us the complete worker logs ? Do you have any traceback in it ? Did you correctly configure your SMTP configuration ?

Tasks are scheduled every 15minutes : https://github.com/opencve/opencve/blob/master/opencve/tasks/__init__.py#L16

**Comment by DaniKawaii** [comment] 2021-01-08 23:01
_Can you give us the complete worker logs ? Do you have any traceback in it ?_
I found out that worker was not running, I think that process stopped at some point or I confused webserver worker with celery one. Now user has received all the mails, one for each report.

About 0 alert reports, when I click one this is the log:
[2021-01-08 19:56:47,549] ERROR in app: Exception on /reports/IMFC8Z9W56BO [GET]
Traceback (most recent call last):
  File "/home/user/.venv/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/user/.venv/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/user/.venv/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/user/.venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/user/.venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/user/.venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/user/.venv/lib/python3.6/site-packages/opencve/controllers/reports.py", line 82, in report
    maximum_score = max([v["max"] for k, v in alerts_sorted.items()])
ValueError: max() arg is an empty sequence

_Did you correctly configure your SMTP configuration ?_
Yes, because this user completed his registration through the email link.

_Tasks are scheduled every 15minutes_
Nice, thanks!

**Comment by ncrocfer** [comment] 2021-01-09 00:16
The problem is not really here, this exception is normal because you have an empty list (0 alerts), so `max([])` will always returns you a `ValueError`. You best need to remove the bad reports from the `reports` table in the database :

```
DELETE FROM reports WHERE public_link = 'xxxxx';
```

The real problem is the reports with 0 alert, they shouldn't exist. The problem seems to be during the report generation, I suspect a problem in your mail server.

1. OpenCVE tries to send the mail : https://github.com/opencve/opencve/blob/v1.0.1/opencve/tasks/reports.py#L139
2. If ok the alerts are closed : https://github.com/opencve/opencve/blob/v1.0.1/opencve/tasks/reports.py#L151

Let's imagine your worker failed here : the alerts will not be closed. 15 minutes later another task will be spawned, with the same error.

I will surround the mail sending with try/except and an error log. I will try to reproduce this problem, but not 100% I will succeed. If you can reproduce it yourself it will help us.

**Comment by DaniKawaii** [comment] 2021-01-11 14:30
Once the worker started and mail server sended all the emails that were pending, the app stopped creating 0 alert reports.
So basically if worker is not active and emails are not being sent, 0 alert reports will be created once every 15 minutes (or the time you have configured for alerts). 
Once emails are sent this problem gets solved, but 0 alert reports remain (and you should delete them one by one of the database to get a clear Reports page):

![image](https://user-images.githubusercontent.com/42950513/104194273-d3327f80-53ff-11eb-8cb6-94fa81e46289.png)

Thank you for your help, now my problem is solved :)
Regards,
DaniKawaii

**Comment by ncrocfer** [comment] 2021-01-11 18:19
Great, happy for you :)

I let this issue opened because I want to know how this is possible to have 0 alert in a report (this is normally not possible because I only iterate on a `users` list fetched from `User.query.filter(User.alerts.any(Alert.notify == False))`.

I don't understand something but I don't know what ^^

**Comment by ncrocfer** [comment] 2021-01-11 18:54
Ok I found, the problem is a missing try/except while sending the email.

The pseudo code is the following (complete code in https://github.com/opencve/opencve/blob/master/opencve/tasks/reports.py) :

```python
# Get  users with alerts to send
users = User.query.filter(User.alerts.any(Alert.notify == False)).all()

# For each of them
for user in users:

    # Get the associated alerts
    alerts = Alert.query.filter_by(user=user, notify=False).all()

    # Create a report
    report = Report(user=user, alerts=alerts)

    # Send the email
    send_mail(report)

    # Close the alerts
    for alert in alerts:
        alert.notify = True
```

If the SMTP is not well configured, OpenCVE raises an exception :

```
$ cat ~/opencve/opencve.cfg
...
smtp_server = foo.bar.bar
smtp_port = 465
smtp_use_tls = True
smtp_username = foo
stmp_password = bar
```
![issue31_1](https://user-images.githubusercontent.com/1552526/104225240-6ee6de80-5446-11eb-836a-9239002a36c4.png)

The code stopped during the `send_mail()` function, so the report was created with the associated alerts, but **these alerts have not been closed** :

![issue31_2](https://user-images.githubusercontent.com/1552526/104225254-727a6580-5446-11eb-85bc-4199666d256b.png)


Then 15 minutes later a new task is launched to review the no-closed alerts. A new report is created with the associated alerts. And because an alert can just have one report, the new report *steals* the alerts of the first one : 

![issue31_3](https://user-images.githubusercontent.com/1552526/104225268-773f1980-5446-11eb-9abe-5f9d8492710d.png)

So in fact the reports have been created with alerts, it's ok for that. But because the code failed before the alerts close, the new report will always appropriate the list of alerts. So the old reports no longer had associated alerts :)

The fix is just to try/except the `send_mail` function. A fix will be released soon ;)

**Comment by DaniKawaii** [comment] 2021-01-11 19:05
Nice! I'm glad you found the cause of the problem, I'm looking forward to the fix 💪 . Thanks for your help and for your hard work 👍 😄

**Closed** 2021-01-12 23:28 UTC
Labels: bug

**Comment by DaniKawaii** [comment] 2021-01-14 19:39
Hello! I updated opencve code with your fix (the try-catch solution) and today 0 alert reports appeared again. This is what I did:
I started beat, worker and then the webserver. All the emails were sent correctly.

![image](https://user-images.githubusercontent.com/42950513/104638074-7267a900-5684-11eb-90df-b40d03b4b021.png)

Then I wanted to try if 0 alert reports would appear again in case worker died, so I stopped worker process and let beat and webserver processes running. After a few hours, webserver gave this error log:

![image](https://user-images.githubusercontent.com/42950513/104639084-c2933b00-5685-11eb-9cba-a95fa2dbc1a2.png)

When I started worker process again, webserver gave the same error log and 0 alert reports appeared in Reports tab:

![image](https://user-images.githubusercontent.com/42950513/104639282-fcfcd800-5685-11eb-830a-a85fccdad40a.png)

![image](https://user-images.githubusercontent.com/42950513/104638560-16e9eb00-5685-11eb-8a28-374792aa6a38.png)

I received one email for each report:

![image](https://user-images.githubusercontent.com/42950513/104638636-3719aa00-5685-11eb-9980-89e924e59d4e.png)

Regards,
Danikawaii

**Comment by ncrocfer** [comment] 2021-01-14 20:05
Sorry but your usage of OpenCVE is weird :)

I don't know how you updated the code (git pull??) but you just have to wait the next release with the new fix (or use `git clone && pip install .`, but you need to be autonomous on this part, I will not help you).

BTW I will explain you how Celery works :

- Celery worker process the tasks,
- Celery beat schedule a task every 15mn
- Webserver only servers the app.

You say me `so I stopped worker process and let beat and webserver processes running. After a few hours, webserver gave this error log [...]`.

Your logs say one report has 0 alert. And as I said before the reports are **only created by worker**. BUT you said me you stopped the worker... So it's really strange : I will not continue my investigation because your version of OpenCVE is in an unknown state (what hash commit???). So my conclusion is : you didn't **DELETE** all your reports with 0 alert. Or you didn't correctly reinstall OpenCVE. I don't know.

Please : upgrade OpenCVE when the new version with the fix will be released (few days). Configure your SMTP. And use OpenCVE normally, with all components running.

If later, **with a propre installation of OpenCVE** and if you still have the same problem you will open a new ticket, with the **Github issue template**. This template is very important to use : it will include useful information like OpenCVE version, Python version, pip freeze and steps to reproduce.
