### ISSUE TITLE
OpenCVE is not compatible with Python >3.8

### ISSUE THREAD

**Issue by Xumeiquer** [opencve/opencve#63] opened 2021-02-18 15:09 UTC
## Expected Behavior
The command `opencve init` works properly.

## Actual Behavior
Using the pip version the command `opencve init` produces an error.

## Steps to Reproduce the Problem
```python
pip install opencve

opencve init
(sbox) PS C:\projects\opencve> opencve init
Traceback (most recent call last):
  File "C:\Program Files\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\projects\opencve\sbox\Scripts\opencve.exe\__main__.py", line 4, in <module>
  File "c:\projects\opencve\sbox\lib\site-packages\opencve\__init__.py", line 10, in <module>
    from opencve.extensions import db
  File "c:\projects\opencve\sbox\lib\site-packages\opencve\extensions.py", line 5, in <module>
    from flask_migrate import Migrate
  File "c:\projects\opencve\sbox\lib\site-packages\flask_migrate\__init__.py", line 11, in <module>
    from alembic import __version__ as __alembic_version__
  File "c:\projects\opencve\sbox\lib\site-packages\alembic\__init__.py", line 3, in <module>
    from . import context  # noqa
  File "c:\projects\opencve\sbox\lib\site-packages\alembic\context.py", line 1, in <module>
    from .runtime.environment import EnvironmentContext
  File "c:\projects\opencve\sbox\lib\site-packages\alembic\runtime\environment.py", line 1, in <module>
    from .migration import MigrationContext
  File "c:\projects\opencve\sbox\lib\site-packages\alembic\runtime\migration.py", line 5, in <module>
    from sqlalchemy import Column
  File "c:\projects\opencve\sbox\lib\site-packages\sqlalchemy\__init__.py", line 8, in <module>
    from . import util as _util  # noqa
  File "c:\projects\opencve\sbox\lib\site-packages\sqlalchemy\util\__init__.py", line 14, in <module>
    from ._collections import coerce_generator_arg  # noqa
  File "c:\projects\opencve\sbox\lib\site-packages\sqlalchemy\util\_collections.py", line 16, in <module>
    from .compat import binary_types
  File "c:\projects\opencve\sbox\lib\site-packages\sqlalchemy\util\compat.py", line 331, in <module>
    time_func = time.clock
AttributeError: module 'time' has no attribute **'clock'**
```
## Specifications

  - OpenCVE version: 1.0.2
  - Python version: python 3.9.1
  - Platform: Windows

## Other

The issue is related to the SQLAlchemy and Flask-SQLAlchemy. They both are using the module `time` and using the functions `clock` which is [deprecated in Python 3.8](https://docs.python.org/3/whatsnew/3.8.html#api-and-feature-removals).

## Potential solutions

* Update the SQLAlchemy and Flask-SQLAlchemy to a newer version.
* Provide a patch

I particularly patched both libraries like so:

Edit: <Python venv>/Lib/site-packages/sqlalchemy/util/compat.py
Replace around line 330:
```Python
if win32 or jython:
        time_func = time.clock
else:
    time_func = time.time
```
By:
```python
if win32 or jython:
    if "clock" in dir(time):
        time_func = time.clock
    else:
        time_func = time.time
else:
    time_func = time.time
```

Edit: <Python venv>/Lib/site-packages/flask_sqlalchemy/__init__.py
Replace around line 38:
```Python
if sys.platform == 'win32':
        _timer = time.clock
else:
    _timer = time.time
```
By:
```python
if sys.platform == 'win32':
    if "clock" in dir(time):
        _timer = time.clock
    else:
        _timer = time.time
else:
    _timer = time.time
```

**Comment by ncrocfer** [comment] 2021-03-28 17:54
Can you try with Python <=3.8 ? List of supported version here : https://github.com/opencve/opencve/blob/master/setup.py#L43

If it works it's a problem on Windows, and as already said OpenCVE doesn't support it. In this case we'll close this issue, because it will not change in the future.

If the problem is still here it means it's linked to Python3.9, which is indeed not yet supported but will of course be. In this case this issue will stay opened until the fix.

**Comment by ncrocfer** [comment] 2021-06-02 06:16
Closed due to inactivity.

**Closed by ncrocfer** 2021-06-02 06:16 UTC
Labels: python3.9
