### ISSUE TITLE
Unable to run Celery worker

### ISSUE THREAD

**Issue by Xumeiquer** [opencve/opencve#66] opened 2021-02-18 17:25 UTC
## Expected Behavior
The command `opencve celery worker -l INFO` works correctly

## Actual Behavior
The command `opencve celery worker -l INFO` throws an error.

## Steps to Reproduce the Problem

```python
C:\projects\opencve> opencve celery worker -l INFO
-------------- celery@hostname v4.3.0 (rhubarb)
---- **** -----
--- * ***  * -- Windows-2012ServerR2-6.3.9600-SP0 2021-02-18 16:43:52
-- * - **** ---
- ** ---------- [config]
- ** ---------- .> app:         opencve:0x8991542820
- ** ---------- .> transport:   redis://127.0.0.1:6379/0
- ** ---------- .> results:     redis://127.0.0.1:6379/1
- *** --- * --- .> concurrency: 2 (prefork)
-- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
--- ***** -----
 -------------- [queues]
                .> celery           exchange=celery(direct) key=celery


[tasks]
  . CVE_UPDATES
  . HANDLE_ALERTS
  . HANDLE_EVENTS
  . HANDLE_REPORTS

[2021-02-18 16:43:52,410: INFO/MainProcess] Connected to redis://127.0.0.1:6379/0
[2021-02-18 16:43:53,660: CRITICAL/MainProcess] Unrecoverable error: AttributeError("'Timer' object has no attribute 'isAlive'")
Traceback (most recent call last):
  File "c:\projects\opencve\sbox\lib\site-packages\celery\worker\worker.py", line 205, in start
    self.blueprint.start(self)
  File "c:\projects\opencve\sbox\lib\site-packages\celery\bootsteps.py", line 119, in start
    step.start(parent)
  File "c:\projects\opencve\sbox\lib\site-packages\celery\bootsteps.py", line 369, in start
    return self.obj.start()
  File "c:\projects\opencve\sbox\lib\site-packages\celery\worker\consumer\consumer.py", line 318, in start
    blueprint.start(self)
  File "c:\projects\opencve\sbox\lib\site-packages\celery\bootsteps.py", line 119, in start
    step.start(parent)
  File "c:\projects\opencve\sbox\lib\site-packages\celery\worker\consumer\heart.py", line 34, in start
    c.heart.start()
  File "c:\projects\opencve\sbox\lib\site-packages\celery\worker\heartbeat.py", line 55, in start
    self.tref = self.timer.call_repeatedly(
  File "c:\projects\opencve\sbox\lib\site-packages\celery\utils\timer2.py", line 130, in call_repeatedly
    return self._do_enter('call_repeatedly', *args, **kwargs)
  File "c:\projects\opencve\sbox\lib\site-packages\celery\utils\timer2.py", line 111, in _do_enter
    self.ensure_started()
  File "c:\projects\opencve\sbox\lib\site-packages\celery\utils\timer2.py", line 105, in ensure_started
    if not self.running and not self.isAlive():
AttributeError: 'Timer' object has no attribute 'isAlive'
[2021-02-18 16:43:54,379: INFO/SpawnPoolWorker-2] child process 4648 calling self.run()
[2021-02-18 16:43:54,379: INFO/SpawnPoolWorker-1] child process 4496 calling self.run()
```
## Specifications

  - OpenCVE version: 1.0.2
  - Python version: 3.9.1
  - Platform: Windows
  - Redis: 2.4.5

**Comment by Xumeiquer** [comment] 2021-02-18 18:26
I've been investigating and the issue is that Python 3.9 has changed the API. The solution is on the Celery side. It might be solved in newer Celery versions, but the newer version has changed the way you invoke the worker. That means you guys have to update that part (task module) of the OpenCVE.

I spot the solution [here](https://github.com/Azure/azure-cli/issues/15441#issuecomment-705400107).

**Comment by ncrocfer** [comment] 2021-03-28 17:53
Can you try with Python <=3.8 ? List of supported version here : https://github.com/opencve/opencve/blob/master/setup.py#L43

If it works it's a problem on Windows, and as already said OpenCVE doesn't support it. In this case we'll close this issue, because it will not change in the future.

If the problem is still here it means it's linked to Python3.9, which is indeed not yet supported but will of course be. In this case this issue will stay opened until the fix.

**Comment by ncrocfer** [comment] 2021-06-02 06:16
Closed due to inactivity.

**Closed by ncrocfer** 2021-06-02 06:16 UTC
Labels: python3.9
