### ISSUE TITLE
Exception when downloading CVEs' database

### ISSUE THREAD

**Issue by DaniKawaii** [opencve/opencve#57] opened 2021-02-05 15:24 UTC
Hi all,
I have configured OpenCVE to download CVEs' database every 60 minutes. OpenCVE is installed in a server (inside a virtual env) and Postgres database is in another server (inside a Docker container). When I run beat, worker and webserver everything works just fine, but after one hour or sometimes a little bit more, when worker is checking for CVEs it gives an exception:
_psycopg2.DatabaseError: could not receive data from server: Connection timed out_

After that, worker tries again (in an hour) to execute the check, and same exception is rised. After a lot of tries, it gives this exception:
_sqlalchemy.exc.InvalidRequestError: Can't reconnect until invalid transaction is rolled back_

While checking traffic with Wireshark, I found out that the packet containing this query is retransmited when exception is raised:
_SELECT metas.id AS metas_id, metas.created_at AS metas_created_at, metas.updated_at AS metas_updated_at, metas.name AS metas_name, metas.value AS metas_value FROM metas WHERE metas.name = 'nvd_last_sha256' LIMIT 1_

Screenshots at the end of this post show logs from worker and Postgres.

If I install OpenCVE (inside virtual env) and Postgres (inside Docker) in the same server or in servers inside the same VLAN, this problem doesn't happen.

## Expected Behavior
Exception should be catched and worker should keep working normally. The app shouldn't stop.

## Actual Behavior
Exception is raised infinitely.

## Steps to Reproduce the Problem

  - Server A and Server B are in different VLANs
  - Install and configure OpenCVE inside a virtual environment in server A
  - Install PostgreSQL on a Docker Container in server B and configure OpenCVE to use this database
  - Allow traffic between both servers (a Firewall rule)
  - Configure OpenCVE's scheduler (beat) to run every 60 minutes ["schedule": timedelta(minutes=60)]
  - Run beat, worker and (optionally) webserver
  - Just let it run for hours until the exception occurs, it's sporadic. Sometimes it takes just one hour, sometimes more than 4 hours.
  
## Specifications

  - OpenCVE version: 1.0.2
  - Python version: 3.6.9
  - Platform: Ubuntu 18.04.5 LTS (Server A) - Ubuntu 18.04.4 LTS (Server B)
  - PostgreSQL version: 13.1

## Screenshots (optional)
Worker's log
![image](https://user-images.githubusercontent.com/42950513/107049275-aa0bd180-67a8-11eb-937c-2e61444529d9.png)

Postgres' log
![image](https://user-images.githubusercontent.com/42950513/107049143-82b50480-67a8-11eb-94c5-bc428c2ad3c9.png)

**Comment by ncrocfer** [comment] 2021-02-06 22:13
Hi @DaniKawaii ,

Maybe I'm wrong but I think the database connection error is not directly linked to OpenCVE but rather to your own firewall configuration. The "Connection timed out" message indicates that OpenCVE failed to connect to your database.

The `sqlalchemy.exc.InvalidRequestError: Can't reconnect until invalid transaction is rolled back` can be fixed by a `db.session.rollback`. I will first try your steps to reproduce the problem to be able to fix it.

I still have a question : why did you change the default scheduling to 1 hour ? (default is 15mn')

**Comment by DaniKawaii** [comment] 2021-02-08 13:16
Hi!
I changed the default scheduling to 1 hour because I'm using this project at work and my boss asked me to change some configurations.

**Comment by ncrocfer** [comment] 2021-02-08 19:09
Yes but why ? Maybe your boss has a reason to ask you that so an option in `opencve.cfg` file can be interesting (such as `periodic_schedule`).
I'm not sure to see the benefit of that, so I ask ;)

**Comment by DaniKawaii** [comment] 2021-02-08 19:45
We are using the system in a centralized way: we created all the users, subscribed them to the same products and configured them to receive a personalized email once a day. That's the reason why we don't need a CVE check so frecuently, as a matter of fact, we could have just configured it once every 24 hours (that would be less "expensive" in terms of connections, downloads, etc.).

I think that a _periodic_schedule_ variable would be a great idea, because every change that I had made outside _opencve.cfg_ was lost after OpenCVE was updated, so I had to edit every file again. Also you should consider creating a variable for the time the once-a-day report is sent (because I had to edit it in the code too). Hope this helps :)

Regards
DaniKawaii

**Comment by ncrocfer** [comment] 2021-02-22 18:08
I didn't succeed to reproduce your problem. Can you please try it in normal condition (ie not modifying the tasks code and let 15mn' of periodicity) ?

**Comment by ncrocfer** [comment] 2021-03-28 17:55
Closing this issue because no answer from initial author.

**Closed by ncrocfer** 2021-03-28 17:55 UTC
